Vagrant.configure("2") do |config|
 config.vm.box = "centos/7"
 config.vm.box_check_update = true

# Create the cent1 Server
config.vm.define "master" do |cent1|
 cent1.vm.hostname = "master"
 cent1.vm.network "private_network", ip: "172.16.0.10"
 cent1.vm.provider "virtualbox" do |v|
  v.name = "master"
  v.memory = 2048
  v.cpus = 2
  v.linked_clone = true
  v.gui = false
end
 cent1.vm.provision "shell", path: "script.sh"
end

# Create the cent2 Server
config.vm.define "node1" do |cent2|
 cent2.vm.hostname = "node1"
 cent2.vm.network "private_network", ip: "172.16.0.11"
 cent2.vm.provider "virtualbox" do |v|
  v.name = "node1"
  v.memory = 1024
  v.cpus = 1
  v.linked_clone = true
  v.gui = false
end
cent2.vm.provision "shell", path: "script.sh"
end

# Create the cent3 Server
config.vm.define "node2" do |cent3|
 cent3.vm.hostname = "node2"
 cent3.vm.network "private_network", ip: "172.16.0.12"
 cent3.vm.provider "virtualbox" do |v|
  v.name = "node2"
  v.memory = 1024
  v.cpus = 1
  v.linked_clone = true
  v.gui = false
end
cent3.vm.provision "shell", path: "script.sh"
end

# Create the cent4 Server
config.vm.define "node3" do |cent4|
 cent4.vm.hostname = "node3"
 cent4.vm.network "private_network", ip: "172.16.0.13"
 cent4.vm.provider "virtualbox" do |v|
  v.name = "node3"
  v.memory = 1024
  v.cpus = 1
  v.linked_clone = true
  v.gui = false
end
cent4.vm.provision "shell", path: "script.sh"
end
end