apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /D/data/tekton # windows
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc
  namespace: tekton-pipelines
spec:
  storageClassName: ""
  volumeName: tekton-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi