apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31002
    - name: slave
      protocol: TCP
      port: 50000
      targetPort: 50000
      nodePort: 31003